name: Contracts CI

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'packages/foodnouns-contracts/**'
      - 'packages/foodnouns-subgraph/**'
    branches:
      - '**'

env:
  NODE_OPTIONS: --max_old_space_size=5120

jobs:
  build_and_test:
    name: Build and Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js 16.20.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.20.0
      - name: Install Yarn
        run: npm install -g yarn
      - run: yarn
      - run: yarn build
      - name: Run contract tests
        run: |
          cd packages/foodnouns-contracts
          yarn test
      - name: Run contract coverage
        run: |
          cd packages/foodnouns-contracts
          yarn coverage
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge build
        run: |
          cd packages/foodnouns-contracts
          forge --version
          forge build --sizes
      - name: Run Forge tests
        run: |
          cd packages/foodnouns-contracts
          forge test -vvv --ffi
